### ISSUE TITLE
kendala login aplikasi

### ISSUE THREAD

**Issue by iqbalakin06** [ajikamaludin/pettycash#1]
![image](https://github.com/ajikamaludin/pettycash/assets/104922959/c4f7a4f1-731d-4577-9462-e61478cfc6b6)

Selamat malam mas ajikamaludin , saya iqbal 
sebelumnya saya ucapkan terimakasih untuk source code yg telah di share
saya ingin menanyakan perihal error cridential ini, bagaimana caranya saya resolve ya untuk bisa login ??

Terimakasih banyak atas jawabannya

**Comment by ajikamaludin-dev** [comment]
Selamat pagi, pastikan sudah menjalankan seeder ya baik itu menggunakan 

```bash
php artisan migrate:refresh --seed
```
maupun menggunakan 

```bash
php artisan db:seed
```

untuk user yang tersedia : 
```
email: kasir@portal.com
password: password
#
email: operation@portal.com
password: password
```

**Comment by iqbalakin06** [comment]
terimakasih banyak mas aji, semoga sukses selalu
